import { SensorConfig } from '../types/sensor'

export const SENSORS: SensorConfig[] = [
  // === PRIMARY PUMP P-101 ===
  {
    id: 'S-P101-VIB',
    name: 'P-101 Vibration',
    type: 'vibration',
    unit: 'mm/s',
    equipmentId: 'P-101',
    min: 0,
    max: 30,
    normalMin: 0.5,
    normalMax: 4.5,
    warningMin: 0,
    warningMax: 7.0,
    baseValue: 2.5,
    noiseAmplitude: 0.3,
    updateIntervalMs: 200,
  },
  {
    id: 'S-P101-TEMP',
    name: 'P-101 Temperature',
    type: 'temperature',
    unit: '°C',
    equipmentId: 'P-101',
    min: 10,
    max: 120,
    normalMin: 35,
    normalMax: 65,
    warningMin: 25,
    warningMax: 80,
    baseValue: 48,
    noiseAmplitude: 1.5,
    updateIntervalMs: 500,
  },
  {
    id: 'S-P101-RPM',
    name: 'P-101 Speed',
    type: 'rpm',
    unit: 'RPM',
    equipmentId: 'P-101',
    min: 0,
    max: 3600,
    normalMin: 1400,
    normalMax: 1800,
    warningMin: 1000,
    warningMax: 2200,
    baseValue: 1500,
    noiseAmplitude: 15,
    updateIntervalMs: 300,
  },

  // === BACKUP PUMP P-102 ===
  {
    id: 'S-P102-VIB',
    name: 'P-102 Vibration',
    type: 'vibration',
    unit: 'mm/s',
    equipmentId: 'P-102',
    min: 0,
    max: 30,
    normalMin: 0.5,
    normalMax: 4.5,
    warningMin: 0,
    warningMax: 7.0,
    baseValue: 2.0,
    noiseAmplitude: 0.2,
    updateIntervalMs: 200,
  },
  {
    id: 'S-P102-TEMP',
    name: 'P-102 Temperature',
    type: 'temperature',
    unit: '°C',
    equipmentId: 'P-102',
    min: 10,
    max: 120,
    normalMin: 35,
    normalMax: 65,
    warningMin: 25,
    warningMax: 80,
    baseValue: 42,
    noiseAmplitude: 1.0,
    updateIntervalMs: 500,
  },

  // === RAW WATER TANK T-201 ===
  {
    id: 'S-T201-LVL',
    name: 'T-201 Level',
    type: 'level',
    unit: '%',
    equipmentId: 'T-201',
    min: 0,
    max: 100,
    normalMin: 30,
    normalMax: 80,
    warningMin: 15,
    warningMax: 90,
    baseValue: 55,
    noiseAmplitude: 0.5,
    updateIntervalMs: 1000,
  },
  {
    id: 'S-T201-TEMP',
    name: 'T-201 Temperature',
    type: 'temperature',
    unit: '°C',
    equipmentId: 'T-201',
    min: 0,
    max: 40,
    normalMin: 12,
    normalMax: 22,
    warningMin: 5,
    warningMax: 28,
    baseValue: 16,
    noiseAmplitude: 0.3,
    updateIntervalMs: 2000,
  },

  // === COAGULATION TANK T-202 ===
  {
    id: 'S-T202-PH',
    name: 'T-202 pH',
    type: 'ph',
    unit: 'pH',
    equipmentId: 'T-202',
    min: 0,
    max: 14,
    normalMin: 6.5,
    normalMax: 7.5,
    warningMin: 6.0,
    warningMax: 8.0,
    baseValue: 7.0,
    noiseAmplitude: 0.05,
    updateIntervalMs: 1000,
  },
  {
    id: 'S-T202-TURB',
    name: 'T-202 Turbidity',
    type: 'turbidity',
    unit: 'NTU',
    equipmentId: 'T-202',
    min: 0,
    max: 100,
    normalMin: 0,
    normalMax: 4.0,
    warningMin: 0,
    warningMax: 8.0,
    baseValue: 2.0,
    noiseAmplitude: 0.3,
    updateIntervalMs: 1000,
  },

  // === PRIMARY FILTER F-301 ===
  {
    id: 'S-F301-PRES',
    name: 'F-301 Pressure',
    type: 'pressure',
    unit: 'bar',
    equipmentId: 'F-301',
    min: 0,
    max: 10,
    normalMin: 1.5,
    normalMax: 3.5,
    warningMin: 1.0,
    warningMax: 5.0,
    baseValue: 2.5,
    noiseAmplitude: 0.1,
    updateIntervalMs: 300,
  },
  {
    id: 'S-F301-FLOW',
    name: 'F-301 Flow Rate',
    type: 'flow_rate',
    unit: 'm³/h',
    equipmentId: 'F-301',
    min: 0,
    max: 200,
    normalMin: 80,
    normalMax: 140,
    warningMin: 50,
    warningMax: 160,
    baseValue: 110,
    noiseAmplitude: 3,
    updateIntervalMs: 500,
  },

  // === SECONDARY FILTER F-302 ===
  {
    id: 'S-F302-PRES',
    name: 'F-302 Pressure',
    type: 'pressure',
    unit: 'bar',
    equipmentId: 'F-302',
    min: 0,
    max: 10,
    normalMin: 1.5,
    normalMax: 3.5,
    warningMin: 1.0,
    warningMax: 5.0,
    baseValue: 2.3,
    noiseAmplitude: 0.08,
    updateIntervalMs: 300,
  },

  // === CLEAR WATER TANK T-303 ===
  {
    id: 'S-T303-LVL',
    name: 'T-303 Level',
    type: 'level',
    unit: '%',
    equipmentId: 'T-303',
    min: 0,
    max: 100,
    normalMin: 40,
    normalMax: 85,
    warningMin: 20,
    warningMax: 95,
    baseValue: 62,
    noiseAmplitude: 0.4,
    updateIntervalMs: 1000,
  },

  // === INTAKE VALVE V-101 ===
  {
    id: 'S-V101-FLOW',
    name: 'V-101 Flow Rate',
    type: 'flow_rate',
    unit: 'm³/h',
    equipmentId: 'V-101',
    min: 0,
    max: 200,
    normalMin: 80,
    normalMax: 140,
    warningMin: 50,
    warningMax: 160,
    baseValue: 115,
    noiseAmplitude: 4,
    updateIntervalMs: 500,
  },
]

export const getSensorById = (id: string) => SENSORS.find(s => s.id === id)
export const getSensorsByEquipment = (equipmentId: string) =>
  SENSORS.filter(s => s.equipmentId === equipmentId)
